source 'https://rubygems.org'

gem 'cucumber'
gem 'rack'
gem 'rack-test'
gem 'capybara'
gem 'net-ssh', '5.2.0'
gem 'net-scp'
gem 'nokogiri'
gem 'rake'
gem 'selenium-webdriver'
gem 'syntax'
gem 'parallel_tests'
