name: RemoteHostTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Generate SSH Key 🔑
      run: ssh-keygen -t rsa -b 4096 -o -f ~/.ssh/id_rsa

    - name: Shutdown SSH Server (SUDO)
      run: sudo systemctl stop ssh

    - uses: actions/checkout@v2

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    

    - name: Pull Docker image
      run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/docker-scp-server:latest

    - name: Run image
      run: |
        docker run -dit --name scp-server \
                   -e AUTHORIZED_KEYS=~/.ssh/id_rsa.pub \
                   -p 22:22 \
                   -v $GITHUB_WORKSPACE/data:/home/data \
                   -v $GITHUB_WORKSPACE/ssh:/var/local/etc/ssh \
                   docker.pkg.github.com/$GITHUB_REPOSITORY/docker-scp-server:latest


    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install cucumber-html-reporter
      run: npm install cucumber-html-reporter

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        SERVER=localhost bundle exec rake parallel:second_stage
        bundle exec rake utils:generate_test_report

    - name: Archive test report artifact
      uses: actions/upload-artifact@v1
      with:
        name: cucumber_report
        path: cucumber_report

